/*
 * CRUD
 *
 * Documentation of our awesome API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type User struct {

	Id string `json:"Id,omitempty"`

	Name string `json:"Name,omitempty"`

	Mail string `json:"Mail,omitempty"`

	Age string `json:"Age,omitempty"`
}
