/*
 * CRUD
 *
 * Documentation of our awesome API.
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"//",
		Index,
	},

	Route{
		"DeleteSTD",
		strings.ToUpper("Delete"),
		"//db/{id}",
		DeleteSTD,
	},

	Route{
		"GetDB",
		strings.ToUpper("Get"),
		"//db",
		GetDB,
	},

	Route{
		"GetSTD",
		strings.ToUpper("Get"),
		"//db/{id}",
		GetSTD,
	},

	Route{
		"NewSTD",
		strings.ToUpper("Post"),
		"//db",
		NewSTD,
	},
}
